### ISSUE TITLE
Reproducible registry provisioning / deployment

### ISSUE THREAD

**Issue by teadur** [internetee/registry#1394]
- [ ]  Implement deployment tool
- [ ]  Allow configuration of cron with the tool #690 
- [ ]  Allow configuration of application / configuration sanity checks #850 #208 #429 
- [ ]  Upgrade Postgres #1354 
- [ ]  Leverage new setup/seed #960 
- [ ] Deploy staging
- [ ] Deploy test
- [ ] Deploy prod
- [ ] Update documentations to reflect new setup
