### ISSUE TITLE
ForceDelete: forcedelete2.0 - new process

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1428]
- [x] Statuses: currently forcedelete marks list of statuses that are set with it (serverRenewProhibited, serverTransferProhibited, serverUpdateProhibited, pendingDelete and serverManualInzone). New process sets only two - serverRenewProhibited, serverTransferProhibited
- [x] New logic - currently force delete is 30 days and started at the moment of admin setting the status. New process is minimum 45 days, but may vary to up to 1 year + 45 days. ForceDelete statuses are set immediately on starting the process, but start of the last 45 days count may be delayed. There are two versions: fast track and soft
  - [x] new parameter - force delete start date marking the beginning of the last 45 day period
  - [x] fast track version - is initiated when the signal of non existent registrant comes from a third party. New set of statuses, 45 day period starts immediately (forcedelete start date is the date forceDelete is initiated), clientHold for removing domain from the zone.
  - [x] soft version - is initiated when invalid registrant data is discovered by the registry. New set of statuses, the last 45 day grace period is postponed for up to a year, clientHold if force delete start date is different from expiration date
    - [x] formula to calculate the force delete start date is: current expiration date - full years of (current expiration date - today's date)
      - [x] if the result is 1 or more calculate and set forcedelete start date
      - [x] else no need to set the date - set statuses will regulate the usage of the domain and unless data is fixed domain registration is expired and released as per regular expiry
- [x] clientHold - new status for removing domain names from zone. client prefix means that registrar is able to remove this status in case they have contact with registrar and the process of fixing the data has begun. This status is used in the last 30 day period only if force delete start date is less than expire date. (In case the last 30 days of force delete overlap with the last 30 days of normal expiration period and the domain registrant data is not fixed and domain registration renewed, registry will automatically set serverHold at the beginning of next day)
  - [x] EPP - remove clientHold status
  - [ ] clientHold removal option to registrar portal (ui and xml console) [#1481 ]
- [x] Stopping force delete process
  - [x] Manual - Admin interface
  - [x] Automatic - registrant change - replacing current registarant object with new valid one automatically stops force delete procedure (statuses are removed, force delete start and force delete dates are removed, whois records are updated) [#1479]
- [x] Notification:
  - [x] EPP poll message on setting the force delete status (Same as with current process) [#1478]
  - [x] Automatic email to all the domain contacts + domain@domain and info@domain addresses to let them know about the start of the last 45 day period (we do this today on regular expirations, but in this case we need to use different e-mail templates) [#1477 ]

Doc: https://docs.google.com/document/d/1rW_YvQ-Ym3ntGdhPLINAfS7ue_GCtrYetbmq0_jHDxM/edit?usp=sharing

**Comment by vohmar** [comment]
Few issues I have spotted:

* In soft force delete the clientHold status is applied together with the force delete it self. The *hold status is not part of forcedelete status set and is applied at the beginning of the last 30day period of the 45 days - the redemption grace period. But it should be preceded by the 15 day expire warning period (this is one of the changes in comparison to current force delete procedure)
* the force delete at is still calculated +30 days - as mentioned in the previous point it should be preceded by 15 days. clientHold or serverHold is applied only during the redemption grace period of 30 days.

**Comment by vohmar** [comment]
* hard force delete sets the force_delete_start time to the beginning of current date (utc). As a result registrant loses up to a day of time to fix the problem. To avoid that the force_delete_start should be set to current datetime value and the count and make the calculations of 15+30 days on top of that. That way registrar gets full 45 days to fix the problems.

testing continues

**Comment by yulgolem** [comment]
Moved force delete dates (start/end) day ahead.

**Comment by vohmar** [comment]
* clientHold status is not set. In registry task start_redemption_grace_period sets serverHold status during normal domain expiration process. The same task should also now handle force delete and set clientHold statuses when the time arrives

**Comment by vohmar** [comment]
https://github.com/internetee/registry/issues/762 needs to be urgently resolved for this task to work. Registrar has to be able to remove clientHold status - adding or removing any other status is not necessary in this context here.

* setting clientHold must also update whois data by setting outzone date value - time of removing domain from zone.

**Comment by vohmar** [comment]
some status that comes with forcedelete seems to prohibit registrar from removing clientHold status. error 2304 Object status prohibits operation is returned

there are 4 statuses associated with the domain
* serverForceDelete
* serverRenewProhibited
* serverTransferProhibited
* clientHold

**Comment by vohmar** [comment]
domain update / registrant change is also prohibited by one of the applied statuses but should not be. serverForceDelete should not block anything on its own. serverRenewProhibited only prohibits domain.renew requests and serverTransferProhibited prohibits only domain.transfer requests all other requests should be available unless there are some other conflicting statuses set.

Messaging:
1. Poll on setting force delete (automatically or manually) - Poll message is already there but lacks the details about the start of the final 45 day countdown
2. Poll message to the registrar when the last 45 day period starts - that one is missing unless hard force delete is initiated by admin.
3. Automatic email to registrant and admin contacts (+info@domain and domain@domain) notifying about the start of the 45 day force delete period. Might use the same logic as the expiration email set 1 day after the start of the expiration period.
4. Poll message on cancellation of force delete period
5. Automatic email on cancellation of force delete period during the last 45 days (contacts are prior informed by EIS about the start of the force delete process)

**Comment by vohmar** [comment]
* registrant change does not cancel force delete automatically
* soft force delete poll message is missing info about the start of the last 45 day period countdown
* in admin deselecting soft delete option also removes option to choose the email template to use for informing domain contacts - in both cases selecting the template is necessary. In case of instant/hard force delete the emails should be sent straight away or with 1 day delay, in case of soft delete the email is sent once the last 45 day period starts (or with 1 day delay to match regular expiration notification model). Here emails are sent instantly in both cases and in hard delete scenario the private registrant template is chosen by default.

**Comment by vohmar** [comment]
this is now done, as all the sub-topics have been resolved. Thank you for the great work guys!
