### ISSUE TITLE
Update Ruby to 2.5

### ISSUE THREAD

**Issue by maciej-szlosarczyk** [internetee/registry#846]
Continuation of #546. Should be done before December 2018 when 2.6 is scheduled to be released.

To upgrade to 2.5, we need:
---
- [x] Upgrade Rails to 4.2.10 #826 
- [x] Upgrade Devise (currently latest 4.4.3 worked just fine)
- [x] Remove `que_mailer` - tracked with #895 
- [x] Fix #651, which uses BigDecimal in the wrong way.
- [x] Upgrade Grape, as it throws multiple deprecation warning on Fixnum/Bignum -> Integer issue. I know we have #691, but getting on a Ruby version with security update is far more critical.
- [x] Upgrade Rails to 5.0 #377
- [x] Upgrade Rails to 5.1
- [x] Upgrade Ruby itself 
- [x] Check mina (`mina-0.3.7/lib/mina/exec_helpers.rb:102: warning: constant ::Fixnum is deprecated`)

**Comment by artur-beljajev** [comment]
@maciej-szlosarczyk Notice use of monkey-patched `builder` gem.

**Comment by artur-beljajev** [comment]
`money` gem supports 2.5 since 6.11.0.
6.11.3 update in #968

**Comment by artur-beljajev** [comment]
https://github.com/rails/rails/pull/23595

**Comment by teadur** [comment]
As of Rails 4.2 is not tested against Ruby 2.5 by upstream ( https://travis-ci.org/rails/rails/builds/516718585 ) we should not consider it supported by Rails 4.2.

Same goes for Rails 5.0  ( https://travis-ci.org/rails/rails/builds/516718340 )
First rails version what is tested against ruby 2.5 is 5.1  ( https://travis-ci.org/rails/rails/builds/516044024 ) 

If possible (we have enough time before Ruby 2.4 end of security support 2020-03)
We should try to upgrade to Rails 5.1 before upgrading Ruby.

If we get time constrained we should upgrade Ruby before getting to Rails 5.1
So for now blocked by #377

**Comment by teadur** [comment]
PG gem needs to be upgraded with rails 5.1 #896

**Comment by vohmar** [comment]
rails raised to 5.1.6
ruby to 2.6.3

closed by #1495
