### ISSUE TITLE
Research and configure javascript testing framework

### ISSUE THREAD

**Issue by maciej-szlosarczyk** [internetee/registry#900]
For certain type of tests, we need a test browser with enabled javascript. For example, #893 would've been caught by a test like that.

## TODO
- [x] Remove Poltergeist (unused, unconfigured)
- [x] Choose appropriate driver (most-likely webdriver)
- [x] Create a new base test class to inherit from
- [x] Configure database_cleaner gem for Minitest
- [x] Update Travis CI configuration
- [x] Update docker config to install required packages inside the docker machine.
- [x] Implement new test for the mobile_id_test
