### ISSUE TITLE
Implement Registrant portal API authentication endpoint

### ISSUE THREAD

**Issue by maciej-szlosarczyk** [internetee/registry#918]
Implement API endpoint that issues tokens based on data from mobile ID and ID card. Should not depend on database authentication, as we currently don't use passwords for such logins. Part of #902 

## TODO

- [x] Find or create users given the identification number and full name.
- [x] Create and encrypt a token
- [x] Implement authentication via bearer token (decrypt the token, check validity, set `current_user`)
- [x] Create base controller and test helpers for both authenticated and unauthenticated scenarios
- [x] Implement ip block on eID authentication
- [x] ~Update module name from `Api` to `API`.~

**Comment by maciej-szlosarczyk** [comment]
Here are the testing notes:

## Positive scenario

- Set up `registrant_api_auth_allowed_ips` environment variable to be the list of IPs you will be making requests from, for example `10.10.10.1, 127.0.0.1`
- Send a POST request to `/api/v1/registrant/auth/eid`, for example with the following JSON body:

```javascript
{ 
  "ident":"30110100103", 
  "first_name":"John", 
  "last_name":"Smith" 
}
```

A user should be found or created, and you should get back a JSON item such as:

```javascript
{
  "access_token":"J62Jslib3GIBo9bIOfngtQ-cnXCxJlfU5-ZxefJ6EujqhKBDvmXqIcM4y7J_ks-D2PIixRXb3OPCTz4hK3P0CBevumvMUuzVuJ3qlQaHoDJZuZNGEXSMR_P1oZ9zjpXxwwMspmeZtCerBwUnHXyZtg==",
  "expires_at":"2018-08-02 08:11:42 UTC",
  "type":"Bearer"
}
```

- Try to get domains data (GET  `/api/v1/registrant/domains`), using the token as authentication header. An example with curl should look something like this:

`curl -H "Authorization: Bearer J62Jslib3GIBo9bIOfngtQ-cnXCxJlfU5-ZxefJ6EujqhKBDvmXqIcM4y7J_ks-D2PIixRXb3OPCTz4hK3P0CBevumvMUuzVuJ3qlQaHoDJZuZNGEXSMR_P1oZ9zjpXxwwMspmeZtCerBwUnHXyZtg==" https://localhost/api/v1/registrant/domains`

You should get back an array of domains or an empty array, in case the person does not have any registered domains. The domains endpoint is just a placeholder for this moment, it does not serve the other functionality required by the API. That is done by #922 

## Negative scenario
Sending requests to `/api/v1/registrant/auth/eid` from an API not set in `registrant_api_auth_allowed_ips` should result in the following error with 401 status:

```javascript
{"errors":["Not authorized"]}
```


 Any tampering with the token, like inserting additional characters, removing characters or using an expired token should result in the following error with a 401 status:

```javascript
{"errors":["Not authorized"]}
```
