### ISSUE TITLE
Implement registry lock for Registrant API

### ISSUE THREAD

**Issue by maciej-szlosarczyk** [internetee/registry#927]
Allow registrant to lock a domain they own or are an person of responsibility for in case of a company domain.

## TODO
- [x] Implement registry lock for domains
- [x] Add functionality to unlock the domains by administrator.
- [x] Expose registry lock via REST API
- [x] Add PaperTrail handling for Registrant API
- [x] Disallow technical contacts from locking a domain.

**Comment by maciej-szlosarczyk** [comment]
Implementation notes, for consultation with @vohmar:

## Lock

Domain can be locked if none of the following statuses is applied: `["pendingDeleteConfirmation", "pendingCreate", "pendingUpdate", "pendingDelete", "pendingRenew", "pendingTransfer", "serverForceDelete"]`.

After lock, the following statuses are applied: `["serverUpdateProhibited", "serverDeleteProhibited", "serverTransferProhibited"]`, as we discussed previously in PR #917.

## Unlock

Domain can be unlocked if all 3 of the statuses are present `["serverUpdateProhibited", "serverDeleteProhibited", "serverTransferProhibited"]`. 

---
If there are additional rules that should be applied to either locking or unlocking a domain, now it's the time to define them.

**Comment by ratM1n** [comment]
tech contact is able to add and remove registry lock
nothing is recorded about who did apply changes - `"updator_str": null`, if changes are made through API
message is sometime misleading - eg. if domains statuses is 'ok', and authorized DELETE is sent, then answer is `{"errors":[{"base":["Domain cannot be unlocked"]}]}` ... maybe "Domain is no locked" is better?

**Comment by maciej-szlosarczyk** [comment]
> nothing is recorded about who did apply changes - "updator_str": null, if changes are made through API
message is sometime misleading - eg. if domains statuses is 'ok', and authorized DELETE is sent, then answer is {"errors":[{"base":["Domain cannot be unlocked"]}]} ... maybe "Domain is no locked" is better?

These two are now fixed. Part of the issue was that our configuration of PaperTrail did not work with changes made by registrants, as they cannot really make any changes in current registrant portal.

The tech contact issue is slightly bigger because of how the relation between RegistrantUsers and DomainContacts is established, but I'm working on it.

**Comment by maciej-szlosarczyk** [comment]
Can be re-tested. Now also includes a change in database schema. `domains.pending_json` becomes jsonb type to allow running `DISTINCT` queries on the table. Please check if the performance of that migration is acceptable.

**Comment by maciej-szlosarczyk** [comment]
Hey @vohmar, it appears that there was an ages-old issue with the domains returned for a registrant user. It should be fixed now, and a registrant who is neither a technical nor an administrative contact should be able to apply a registry lock.
